project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!archive/"

execute:
  freeze: auto

website:
  title: "Andreas Haupt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: team.qmd
        text: Team
      - href: cv.qmd
        text: CV

format:
  html:
    toc: false
    theme:
      light: theme-light.scss
      dark: theme-dark.scss
    include-after-body: navbar-scroll.html
